# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b76cbd98a49cb6bab70b2a887f437fa0fa3f2dafa62f75456935f5315b8d9a00cb1574dd54303b1791549dba5cad4f8889f33146eb7245e57d6335f34c846d5

test:
  secret_key_base: 0ad9f6e5238ed407cb053b4eee517e15b7c98f54680806039dac4eeadbf466b9b6ab60084a5f475fe09d32c5f7abc6f8dd11b0347167242a12c3c4ccb3e7c448

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
